### ISSUE TITLE
action: 'postback' in options always triggering and opening new tab

### ISSUE THREAD

**Issue by xpediteur** [bonnak/vue-chat-bot#37]
Hello,

I use vue-bot-ui in my vue2 apps and it works great. I have a question that I can't solve from the code.

I use this object to create a button

{
              text: 'or Support Ticket',
              value: '',
              action: this.postback() // Request to API
}

and to call the function postback(). ( in my methods )

However, this function is always triggered when the app is called up ( in botStart ) and when the button is pressed, a new tab is always opened in the browser. How I can fix this? I only want to call the function postback() and do any API stuff there without opening a new tab.

Thanks for helping with this issue.

**Comment by juzser** [comment]
@xpediteur 
I think you just have to change the action line to `action: this.postback`
It should work.

**Comment by xpediteur** [comment]
OK, thank you very much for that advice, that's much better, but a new browser tab will still be opened!

**Comment by xpediteur** [comment]
so, this code works now, but the "text" is send to messageSendHandler and it shouldn't be.
            {
              text: 'Support Ticket erstellen',
              value: this.postback,
              action: 'postback' // Request to API
            }

**Comment by juzser** [comment]
Firstly, you should create issue on my original repo, not yours. So I will not answer here.

Second, I think you’re using the package totally wrong. The action ‘postback’ is fixed, and you have to check in the msg-send event. Just read the doc carefully.

**Comment by xpediteur** [comment]
THX a lot. Very kind of you. I understand to logic behind now. I will do my stuff im msg-send when value.action is e.g. ‚postback.'

Greetings
Ralf



Am 15.02.2023 um 16:39 schrieb Son Nguyen H. ***@***.***>:


Firstly, you should create issue on my original repo, not yours. So I will not answer here.

Second, I think you’re using the package totally wrong. The action ‘postback’ is fixed, and you have to check in the msg-send event. Just read the doc carefully.
